#!/usr/bin/env bash
# a comment
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
string="server_name 1820.tech;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$string/" /etc/nginx/sites-available/default
service nginx restart

