#!/usr/bin/env bash
# comment
sudo apt-get -y update
sudo apt-get -y upgrade

echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html


sudo sed -i "s/server_name _;/server_name 1820.tech;\n\tlocation \/ {\n\t\t#redirect task\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

service nginx restart
