#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
COUNTER=0
while [ $COUNTER -lt 10 ];
do
    (( COUNTER++ )) || true
if [ $COUNTER -eq 4 ];
then
    echo "bad luck"
elif [ $COUNTER -eq 8 ];
then
    echo "good luck"
else
    echo "Holberton School"
fi
done
