#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
HOUR=0
while [ $HOUR -le 13 ];
do
    if [ $HOUR -eq 0 ];
    then
        echo "Hour: $HOUR"
    else
        MINUTE=1
        while [ $MINUTE -lt 60 ];
        do
            echo "$MINUTE"
            (( MINUTE++ )) || true
        done
        if [ ! $HOUR -eq 13 ];
        then
            echo "Hour: $HOUR"
        fi
    fi
        (( HOUR++ )) || true
done
