#!/usr/bin/env bash
# comment 
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost/g" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
tail -n +2 /etc/hosts >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
