#!/usr/bin/env bash
cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.2 localhost/g" ~/host.new
sed -i "s/.*facebook.com//g" ~hosts.new
echo "8.8.8.8 facebook.com" >> 
ast.new
cat ~/hosts.new > etc/hosts 
